name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install doctl 
      uses: digitalocean/action-doctl@v2.1.0
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Log in to DO Container Registry 
      run: doctl registry login --expiry-seconds 600

    - name: DigitalOcean Build and Publish Docker Image
      uses: ripplr-io/docr-docker-publish@v1
      with:
        image_path: unlimitedapp/captcha
        dockerfile: ./Dockerfile
        docker_build_context: ./
